[build]
  publish = "."

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/"
  to   = "/OFS_BlackSeal.html"
  status = 200

[[redirects]]
  from = "/home"
  to   = "/OFS_Home.html"
  status = 301
